### ISSUE TITLE
DO NOT MAKE CHANGES TO YOUR REPOSITORY AS ROOT!!!!!!

### ISSUE THREAD

**Issue by ibara** [Websys-ApartMATE/ApartMATE#9]
Someone (Lauren, I believe) is authoring and committing changes to the repository as root (see image at the bottom of this message). That is very dangerous; please set your user name and email by running these commands on your terminal:
```
git config --global user.name myname
git config --global user.email myemail@example.com
```
![root](https://user-images.githubusercontent.com/3883351/69770915-c64dc080-1158-11ea-8797-8255ff997ad3.png)

**Comment by ibara** [comment]
Ping ping ping ping ping ping ping
@Chromelia @Erastos @molly34762 @laurenroy

**Comment by Erastos** [comment]
@ibara. The change has been made. Is there anything else that needs to be taken care of regarding this matter?

**Comment by ibara** [comment]
Usually, it's a sign that the person is doing all their work as root (and that is the dangerous bit). As long as that's not happening, then all is good.

**Comment by laurenroy** [comment]
Yes, I apologize for that. I didn't realize that was happening, but I have fixed it now.

**Comment by ibara** [comment]
OK, sounds good then.
